using API.Entities;
using Microsoft.EntityFrameworkCore;


namespace API.Data
{
    public class DataContext : DbContext
    {
        // autogenerated with period + space -> generate constructor
        public DataContext(DbContextOptions options) : base(options)
        {
        }
        // prop tab+tab to autogenerate
        // database for AppUser
        // table name = Users
        public DbSet<AppUser> Users { get; set; }

    }
}